name: main

on:
  # Enable manually triggered workflow runs
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build, Test and Publish
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Test with Maven
        working-directory: Java
        run: mvn -B -pl libraries/recognizers-text -pl libraries/recognizers-text-number -pl libraries/recognizers-text-number-with-unit -pl libraries/recognizers-text-choice -pl libraries/recognizers-text-date-time -pl libraries/recognizers-text-datatypes-timex-expression -pl libraries/recognizers-text-sequence clean install -am
      - name: Publish Internal Microsoft Recognizers Text
        working-directory: Java
        run: mvn -B -pl libraries/recognizers-text -pl libraries/recognizers-text-number -pl libraries/recognizers-text-number-with-unit -pl libraries/recognizers-text-choice -pl libraries/recognizers-text-date-time -pl libraries/recognizers-text-datatypes-timex-expression -pl libraries/recognizers-text-sequence -DskipTests -Dcheckstyle.skip deploy -am
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

